version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  # build and deploy front end files
  build_deploy_front:
    environment: 
      COMMIT_MESSAGE: $(git log --format=oneline -n 1 $CIRCLE_SHA1)
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: |
            echo $COMMIT_MESSAGE
            sudo npm install -g npm@latest
            sudo npm i -g @quasar/cli
      - node/install-packages:
          app-dir: "./cardCraft-front"
          cache-path: ./node_modules
          override-ci-command: npm install
      - run: 
          name: Build and compile files
          command: |
            cd cardCraft-front
            quasar build
      - run:
          name: Deploy front via FTP
          command: |
            sudo apt-get update
            sudo apt-get install -y lftp

  #lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; mirror -R --delete ./cardCraft-front/dist/spa /public; bye"
  # build and deploy api files
  build_deploy_api:
    docker:
      - image: cimg/php:8.3.2
    steps:
      - checkout
      - run:
          name: Deploy api via FTP
          command: |
            sudo apt-get update
            sudo apt-get install -y lftp
            lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; mirror -R --delete ./cardCraft-api /api; bye"
      
# Orchestrate our job run sequence
workflows:
  build_and_deploy:
    jobs:
      - build_deploy_front
      #- build_deploy_api
