version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
  build_deploy_front:
    docker:
      - image: cimg/node:lts-browsers
    environment:
      SKIP_FRONT_DEPLOY: true
    steps:
      - checkout
      - run:
          name: "Setup custom environment variables"
          command: |
            export COMMIT_MSG=$(git log --format=%B -n 1 $CIRCLE_SHA1)
            echo "Commit Message: $COMMIT_MSG"
            if [[ $COMMIT_MSG == *"@backOnly"* ]]; then
              echo "Skipping front deploy"
              exit 0
            else
              echo "Continue deploy"
            fi
      - run:
          name: Install dependencies
          command: |
            sudo npm install -g npm@latest
            sudo npm i -g @quasar/cli
      - node/install-packages:
          app-dir: "./cardCraft-front"
          cache-path: ./node_modules
          override-ci-command: npm install
      - run:
          name: Build and compile files
          command: |
            cd cardCraft-front
            quasar build
      - run:
          name: Deploy front via FTP
          command: |
            if [ -z "$SKIP_FRONT_DEPLOY" ]; then
              sudo apt-get update
              sudo apt-get install -y lftp
              # Actual deployment commands go here
            else
              echo "Skipping front deployment based on condition"
            fi

workflows:
  version: 2
  deploy:
    jobs:
      - build_deploy_front
