version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build_front:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - node/install-packages:
          cache-path: ./node_modules
          override-ci-command: npm install
      - run: 
          name: Build and compile files
          command: |
            cd cardCraft-front
            ls -la
            quasar build
      # - run:
      #     name: Deploy via FTP
      #     command: |
      #       sudo apt-get update
      #       sudo apt-get install -y lftp
      #       lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; mirror -R --delete ./dist /; bye"
      
# Orchestrate our job run sequence
workflows:
  build_and_deploy:
    jobs:
      - build_front
