version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  # build and deploy front end files
  build_deploy_front:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run:
          name: "Setup custom environment variables"
          command: |
            echo "export COMMIT_MSG=\"$(git log --format=oneline -n 1 $CIRCLE_SHA1)\"" >> $BASH_ENV
            if [[ "$COMMIT_MSG" == *"@frontOnly"* ]] ; then export FRONT_ONLY="true"; else export FRONT_ONLY="false"; fi
      - run: 
          name: Install dependencies
          command: |
            echo ${COMMIT_MSG}
            sudo npm install -g npm@latest
            sudo npm i -g @quasar/cli
      - node/install-packages:
          app-dir: "./cardCraft-front"
          cache-path: ./node_modules
          override-ci-command: npm install
      - run: 
          name: Build and compile files
          command: |
            cd cardCraft-front
            quasar build
      - run:
          name: Deploy front via FTP
          command: |
            sudo apt-get update
            sudo apt-get install -y lftp

  #lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; mirror -R --delete ./cardCraft-front/dist/spa /public; bye"
  # build and deploy api files
  build_deploy_api:
    docker:
      - image: cimg/php:8.3.2
    steps:
      - checkout
      - run:
          name: Deploy api via FTP
          command: |
            sudo apt-get update
            sudo apt-get install -y lftp
            lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; mirror -R --delete ./cardCraft-api /api; bye"
      
# Orchestrate our job run  sequence
workflows:
  front:
    when:
      condition:
        equal: [ true, $COMMIT_MSG == *"@frontOnly"* ]
      condition: 
    jobs:
      - build_deploy_front
      #- build_deploy_api
  # back:
  #   when:
  #     condition: false
  #   jobs:
      #- build_deploy_api
